name: Python Package using Conda

on:
  push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Add conda to system path
      run: |
        echo "source activate myenv" >> $HOME/.bashrc
        conda init bash
        source $HOME/.bashrc

    - name: Install dependencies
      run: |
        conda activate myenv
        conda install pandas==1.3.3
        conda install -c conda-forge --file requirements.txt

    - name: Run Python script
      run: python carga_de_datos_db.py

    - name: Lint with flake8
      run: |
        conda install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: pytest
